name: ExtreamTools
version: ${version}
api-version: 1.16
main: net.mslx.extreamtools.Main
commands:
  spawn:
    description: Teleport to spawn
  setspawn:
    description: Set the spawn point
  god:
    description: Enable God mode
  fly:
    description: Enable fly mode
  heal:
    description: Heal yourself
  feed:
    description: Fill your hunger bar
